version: "3"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
  flyway:
    image: flyway/flyway:9-alpine
    command: -configFiles=/flyway/conf/base.config,/flyway/conf/dev.config migrate #Includes sample data
    volumes:
      #Main
      - ./migrations/main:/flyway/sql/main
      - ./config/base.config:/flyway/conf/base.config
      #Dev
      - ./migrations/dev-seed:/flyway/sql/dev-seed
      - ./config/dev.config:/flyway/conf/dev.config
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DEFAULT_USER_EMAIL=${DEFAULT_USER_EMAIL}
      - DEFAULT_USER_PHOTO_URL=${DEFAULT_USER_PHOTO_URL}
      - DEFAULT_USER_EXTERNAL_ID=${DEFAULT_USER_EXTERNAL_ID}
    depends_on:
      - postgres
